version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
